const WEB = 'Web';
const REACT = 'ReactJS';
const POSTGRESQL = 'PostgreSQL';
const JAVASCRIPT = 'Javascript';
const P5 = 'p5';
const UNITY = 'Unity';
const CS = 'C#';
const PHP = 'PHP';
const ANDROID = 'Android Studio'
const JAVA = 'Java';
const PYTHON = 'Python';
const TERMINAL = 'Terminal application';
const RESEARCH = 'Research';
const NUMPY = 'Numpy';
const PROTOTYPING = 'Prototyping';
const POSTER = 'Poster';
const ADOBEXD = 'Adobe XD';
const ILLUSTRATOR = 'Illustrator';
const PHOTOSHOP = 'Photoshop';

export const DESIGN = 'Graphic Design';
export const PROGRAMMING = 'Programming';
export const GENART_TAGS = [PROGRAMMING, WEB, JAVASCRIPT, REACT, P5, POSTGRESQL, PHP];
export const RADISH_TAGS = [PROGRAMMING, UNITY, CS];
export const GO_TAGS = [PROGRAMMING, ANDROID, JAVA];
export const WORDCO_TAGS = [PROGRAMMING, PYTHON, NUMPY, TERMINAL, RESEARCH]; 
export const SCREENPRINTING_TAGS = [DESIGN, POSTER, ILLUSTRATOR, PHOTOSHOP];
export const TYPOMANIE_TAGS = [DESIGN, PROTOTYPING, ADOBEXD, ILLUSTRATOR];